apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deploy
spec:
  replicas:
    matchLabels:
      env: production
  template:
    metadata:
      name: web-pod
      labels:
        env: production
    spec:
      containers:
      - name: httpd
        image: akansh028/jenkins-slave-maven
